var SECTORS = [
    { id:"food_hospitality", label:"Restaurants & cafes", base:88, defaultOn:true,
      why:"Food is the most Instagram-native product there is \u2014 Reels, UGC, and delivery-app photos convert directly into foot traffic." },
    { id:"beauty_wellness", label:"Beauty, fitness & wellness", base:86, defaultOn:true,
      why:"Before/after content, transformation Reels, and booking-driven ads are practically built for this category." },
    { id:"leisure_entertainment", label:"Leisure & entertainment", base:80, defaultOn:true,
      why:"Experience-driven businesses thrive on short-form video that shows the fun rather than describes it." },
    { id:"hospitality_lodging", label:"Hotels & lodging", base:82, defaultOn:true,
      why:"Guests book on vibe \u2014 strong photo/video content and Meta ads directly move occupancy." },
    { id:"retail_general", label:"Independent shops & boutiques", base:78, defaultOn:true,
      why:"Product-forward and highly visual \u2014 an easy fit for Reels, Canva graphics, and UGC-style ads." },
    { id:"retail_big_ticket", label:"Big-ticket retail", base:76, defaultOn:true,
      why:"High-value items justify paid Meta ad spend, and video walkthroughs build trust before a big purchase." },
    { id:"real_estate", label:"Real estate", base:75, defaultOn:true,
      why:"Listings are inherently visual \u2014 property tours, Reels, and targeted Meta ads sell homes faster." },
    { id:"retail_chain", label:"Retail chains", base:72, defaultOn:true,
      why:"Multi-location brands need consistent content and paid social managed centrally \u2014 a natural retainer fit." },
    { id:"food_retail", label:"Food & grocery retail", base:68, defaultOn:true,
      why:"Fresh product shots and seasonal promos give a steady stream of easy content ideas." },
    { id:"childcare", label:"Childcare & family services", base:66, defaultOn:true,
      why:"Parents choose on trust and warmth \u2014 authentic photo/video content is the deciding factor." },
    { id:"trades_repair", label:"Trades & repair", base:64, defaultOn:true,
      why:"Before/after job photos and local Facebook/Meta ads are a proven lead-gen channel most of these businesses ignore." },
    { id:"healthcare", label:"Healthcare & clinics", base:63, defaultOn:true,
      why:"Patient education content and a clean, trustworthy social presence drives new-patient bookings." },
    { id:"education_training", label:"Education & training", base:62, defaultOn:true,
      why:"Course previews, testimonials, and short-form explainer content directly drive enrollments." },
    { id:"construction", label:"Construction", base:60, defaultOn:true,
      why:"Project reveal content and case-study Reels build the trust needed for high-value bids." },
    { id:"marketing_media", label:"Marketing & media", base:58, defaultOn:false,
      why:"Already in the content game themselves \u2014 more likely a competitor or partner than a client." },
    { id:"professional_services", label:"Professional services", base:55, defaultOn:true,
      why:"LinkedIn content and personal-brand positioning helps these firms win higher-value clients." },
    { id:"insurance_finance", label:"Insurance & finance", base:48, defaultOn:false,
      why:"Trust-building content helps, but sales cycles are long and regulation limits creative freedom." },
    { id:"it_tech_services", label:"IT & telecom", base:46, defaultOn:false,
      why:"B2B and less visual \u2014 LinkedIn content can help, but it's a slower, harder social media sell." },
    { id:"general_office", label:"General offices", base:38, defaultOn:false,
      why:"Unclear business type and little visual content to build a social strategy around." },
    { id:"logistics_transport", label:"Logistics & transport", base:40, defaultOn:false,
      why:"Low visual appeal and mostly B2B \u2014 social media has less direct impact on their sales." },
    { id:"banks_financial_institutions", label:"Bank branches", base:35, defaultOn:false,
      why:"Heavily regulated and rarely the decision-maker for local marketing spend." }
];

// [osmKey, osmValue, sectorId, brandRequired?] -- brandRequired filters out one-off
// independent shops for categories where they'd otherwise flood the results.
var TAGMAP = [
    ["office","estate_agent","real_estate",false],
    ["office","insurance","insurance_finance",false],
    ["office","financial","insurance_finance",false],
    ["office","accountant","professional_services",false],
    ["office","tax_advisor","professional_services",false],
    ["office","advertising_agency","marketing_media",false],
    ["office","logistics","logistics_transport",false],
    ["office","moving_company","logistics_transport",false],
    ["office","courier","logistics_transport",false],
    ["office","company","general_office",false],
    ["office","coworking","general_office",false],
    ["office","lawyer","professional_services",false],
    ["office","notary","professional_services",false],
    ["office","consulting","professional_services",false],
    ["office","employment_agency","professional_services",false],
    ["office","recruitment","professional_services",false],
    ["office","architect","professional_services",false],
    ["office","engineer","professional_services",false],
    ["office","surveyor","professional_services",false],
    ["office","research","professional_services",false],
    ["office","it","it_tech_services",false],
    ["office","telecommunication","it_tech_services",false],
    ["office","newspaper","marketing_media",false],
    ["office","publisher","marketing_media",false],
    ["shop","supermarket","retail_chain",false],
    ["shop","mall","retail_chain",false],
    ["shop","department_store","retail_chain",false],
    ["shop","variety_store","retail_chain",false],
    ["shop","doityourself","retail_chain",false],
    ["shop","convenience","retail_general",false],
    ["shop","car","retail_big_ticket",false],
    ["shop","motorcycle","retail_big_ticket",false],
    ["shop","appliance","retail_big_ticket",false],
    ["shop","electronics","retail_big_ticket",false],
    ["shop","furniture","retail_big_ticket",false],
    ["shop","jewelry","retail_big_ticket",false],
    ["shop","watches","retail_big_ticket",false],
    ["shop","tiles","retail_big_ticket",false],
    ["shop","carpet","retail_big_ticket",false],
    ["shop","bathroom_furnishing","retail_big_ticket",false],
    ["shop","kitchen","retail_big_ticket",false],
    ["shop","bed","retail_big_ticket",false],
    ["shop","car_parts","retail_general",false],
    ["shop","bicycle","retail_general",false],
    ["shop","hardware","retail_general",false],
    ["shop","clothes","retail_general",false],
    ["shop","shoes","retail_general",false],
    ["shop","fashion","retail_general",false],
    ["shop","bag","retail_general",false],
    ["shop","books","retail_general",false],
    ["shop","stationery","retail_general",false],
    ["shop","toys","retail_general",false],
    ["shop","games","retail_general",false],
    ["shop","video_games","retail_general",false],
    ["shop","sports","retail_general",false],
    ["shop","outdoor","retail_general",false],
    ["shop","pet","retail_general",false],
    ["shop","florist","retail_general",false],
    ["shop","garden_centre","retail_general",false],
    ["shop","houseware","retail_general",false],
    ["shop","lighting","retail_general",false],
    ["shop","curtain","retail_general",false],
    ["shop","gift","retail_general",false],
    ["shop","party","retail_general",false],
    ["shop","leather","retail_general",false],
    ["shop","fabric","retail_general",false],
    ["shop","sewing","retail_general",false],
    ["shop","e-cigarette","retail_general",false],
    ["shop","kiosk","retail_general",false],
    ["shop","newsagent","retail_general",false],
    ["shop","second_hand","retail_general",false],
    ["shop","charity","retail_general",false],
    ["shop","frame","retail_general",false],
    ["shop","trade","retail_general",false],
    ["shop","model","retail_general",false],
    ["shop","musical_instrument","retail_general",false],
    ["shop","music","retail_general",false],
    ["shop","art","retail_general",false],
    ["shop","video","retail_general",false],
    ["shop","computer","retail_general",false],
    ["shop","chemist","retail_general",false],
    ["shop","general","retail_general",false],
    ["shop","interior_decoration","professional_services",false],
    ["shop","travel_agency","professional_services",false],
    ["shop","copyshop","professional_services",false],
    ["shop","photo","professional_services",false],
    ["shop","storage_rental","professional_services",false],
    ["shop","funeral_directors","professional_services",false],
    ["shop","laundry","trades_repair",false],
    ["shop","dry_cleaning","trades_repair",false],
    ["shop","locksmith","trades_repair",false],
    ["shop","tyres","trades_repair",false],
    ["shop","mobile_phone","retail_chain",true],
    ["shop","hairdresser","beauty_wellness",false],
    ["shop","beauty","beauty_wellness",false],
    ["shop","cosmetics","beauty_wellness",false],
    ["shop","optician","healthcare",false],
    ["shop","bakery","food_retail",false],
    ["shop","butcher","food_retail",false],
    ["shop","greengrocer","food_retail",false],
    ["shop","deli","food_retail",false],
    ["shop","confectionery","food_retail",false],
    ["shop","seafood","food_retail",false],
    ["shop","alcohol","food_retail",false],
    ["shop","wine","food_retail",false],
    ["shop","coffee","food_retail",false],
    ["shop","tea","food_retail",false],
    ["shop","pastry","food_retail",false],
    ["shop","farm","food_retail",false],
    ["shop","pawnbroker","banks_financial_institutions",false],
    ["shop","money_lender","banks_financial_institutions",false],
    ["shop","bookmaker","leisure_entertainment",false],
    ["amenity","bank","banks_financial_institutions",false],
    ["amenity","bureau_de_change","banks_financial_institutions",false],
    ["amenity","hospital","healthcare",false],
    ["amenity","clinic","healthcare",false],
    ["amenity","dentist","healthcare",false],
    ["amenity","veterinary","healthcare",false],
    ["amenity","pharmacy","healthcare",false],
    ["amenity","doctors","healthcare",false],
    ["amenity","restaurant","food_hospitality",true],
    ["amenity","fast_food","food_hospitality",true],
    ["amenity","cafe","food_hospitality",true],
    ["amenity","bar","food_hospitality",true],
    ["amenity","pub","food_hospitality",true],
    ["amenity","ice_cream","food_hospitality",true],
    ["amenity","fuel","retail_chain",true],
    ["amenity","car_wash","trades_repair",false],
    ["amenity","car_rental","logistics_transport",false],
    ["amenity","cinema","leisure_entertainment",false],
    ["amenity","theatre","leisure_entertainment",false],
    ["amenity","nightclub","leisure_entertainment",false],
    ["amenity","casino","leisure_entertainment",false],
    ["amenity","gambling","leisure_entertainment",false],
    ["amenity","events_venue","leisure_entertainment",false],
    ["amenity","conference_centre","professional_services",false],
    ["amenity","university","education_training",false],
    ["amenity","college","education_training",false],
    ["amenity","driving_school","education_training",false],
    ["amenity","language_school","education_training",false],
    ["amenity","music_school","education_training",false],
    ["amenity","kindergarten","childcare",false],
    ["amenity","childcare","childcare",false],
    ["amenity","coworking_space","general_office",false],
    ["amenity","internet_cafe","retail_general",false],
    ["amenity","fitness_centre","beauty_wellness",false],
    ["amenity","gym","beauty_wellness",false],
    ["amenity","spa","beauty_wellness",false],
    ["amenity","marketplace","retail_chain",false],
    ["amenity","car_sharing","logistics_transport",false],
    ["amenity","taxi","logistics_transport",false],
    ["craft","builder","construction",false],
    ["craft","electrician","trades_repair",false],
    ["craft","plumber","trades_repair",false],
    ["craft","carpenter","trades_repair",false],
    ["craft","hvac","trades_repair",false],
    ["craft","roofer","trades_repair",false],
    ["craft","painter","trades_repair",false],
    ["craft","tiler","trades_repair",false],
    ["craft","metal_construction","trades_repair",false],
    ["craft","locksmith","trades_repair",false],
    ["craft","photographer","professional_services",false],
    ["craft","tailor","trades_repair",false],
    ["craft","shoemaker","trades_repair",false],
    ["craft","upholsterer","trades_repair",false],
    ["craft","gardener","trades_repair",false],
    ["craft","brewery","food_retail",false],
    ["craft","winery","food_retail",false],
    ["craft","distillery","food_retail",false],
    ["healthcare","hospital","healthcare",false],
    ["healthcare","clinic","healthcare",false],
    ["healthcare","dentist","healthcare",false],
    ["healthcare","physiotherapist","healthcare",false],
    ["healthcare","optometrist","healthcare",false],
    ["healthcare","alternative","healthcare",false],
    ["healthcare","laboratory","healthcare",false],
    ["healthcare","midwife","healthcare",false],
    ["healthcare","rehabilitation","healthcare",false],
    ["healthcare","psychotherapist","healthcare",false],
    ["healthcare","pharmacy","healthcare",false],
    ["tourism","hotel","hospitality_lodging",false],
    ["tourism","motel","hospitality_lodging",false],
    ["tourism","guest_house","hospitality_lodging",false],
    ["tourism","hostel","hospitality_lodging",false],
    ["tourism","apartment","hospitality_lodging",false],
    ["tourism","chalet","hospitality_lodging",false],
    ["tourism","zoo","leisure_entertainment",false],
    ["tourism","theme_park","leisure_entertainment",false],
    ["tourism","aquarium","leisure_entertainment",false],
    ["tourism","gallery","professional_services",false],
    ["leisure","fitness_centre","beauty_wellness",false],
    ["leisure","sports_centre","leisure_entertainment",false],
    ["leisure","golf_course","leisure_entertainment",false],
    ["leisure","water_park","leisure_entertainment",false],
    ["leisure","bowling_alley","leisure_entertainment",false],
    ["leisure","escape_game","leisure_entertainment",false],
    ["leisure","dance","beauty_wellness",false]
];
