"""
Source of truth for Signal's lead-scoring sectors and OSM tag mappings.

Edit this file, then run:  python3 build_sectors.py
That regenerates sectors.js -- the file index.html actually loads in the browser.
This .py file is never read by the browser; it only exists so the data can be
edited/maintained in Python instead of hand-edited JS.

Scoring is tuned for Blazeup Digital: a social media / content / AI video agency.
Higher base scores go to visually-driven, consumer-facing businesses that live
or die on Instagram/TikTok/Facebook presence -- restaurants, salons, hotels,
gyms -- since that's the easiest pitch ("your competitors are outposting you").
Lower scores go to B2B/back-office categories with little visual content to work with.
"""

SECTORS = [
    {"id": "food_hospitality", "label": "Restaurants & cafes", "base": 88, "defaultOn": True,
     "why": "Food is the most Instagram-native product there is \u2014 Reels, UGC, and delivery-app photos convert directly into foot traffic."},
    {"id": "beauty_wellness", "label": "Beauty, fitness & wellness", "base": 86, "defaultOn": True,
     "why": "Before/after content, transformation Reels, and booking-driven ads are practically built for this category."},
    {"id": "leisure_entertainment", "label": "Leisure & entertainment", "base": 80, "defaultOn": True,
     "why": "Experience-driven businesses thrive on short-form video that shows the fun rather than describes it."},
    {"id": "hospitality_lodging", "label": "Hotels & lodging", "base": 82, "defaultOn": True,
     "why": "Guests book on vibe \u2014 strong photo/video content and Meta ads directly move occupancy."},
    {"id": "retail_general", "label": "Independent shops & boutiques", "base": 78, "defaultOn": True,
     "why": "Product-forward and highly visual \u2014 an easy fit for Reels, Canva graphics, and UGC-style ads."},
    {"id": "retail_big_ticket", "label": "Big-ticket retail", "base": 76, "defaultOn": True,
     "why": "High-value items justify paid Meta ad spend, and video walkthroughs build trust before a big purchase."},
    {"id": "real_estate", "label": "Real estate", "base": 75, "defaultOn": True,
     "why": "Listings are inherently visual \u2014 property tours, Reels, and targeted Meta ads sell homes faster."},
    {"id": "retail_chain", "label": "Retail chains", "base": 72, "defaultOn": True,
     "why": "Multi-location brands need consistent content and paid social managed centrally \u2014 a natural retainer fit."},
    {"id": "food_retail", "label": "Food & grocery retail", "base": 68, "defaultOn": True,
     "why": "Fresh product shots and seasonal promos give a steady stream of easy content ideas."},
    {"id": "childcare", "label": "Childcare & family services", "base": 66, "defaultOn": True,
     "why": "Parents choose on trust and warmth \u2014 authentic photo/video content is the deciding factor."},
    {"id": "trades_repair", "label": "Trades & repair", "base": 64, "defaultOn": True,
     "why": "Before/after job photos and local Facebook/Meta ads are a proven lead-gen channel most of these businesses ignore."},
    {"id": "healthcare", "label": "Healthcare & clinics", "base": 63, "defaultOn": True,
     "why": "Patient education content and a clean, trustworthy social presence drives new-patient bookings."},
    {"id": "education_training", "label": "Education & training", "base": 62, "defaultOn": True,
     "why": "Course previews, testimonials, and short-form explainer content directly drive enrollments."},
    {"id": "construction", "label": "Construction", "base": 60, "defaultOn": True,
     "why": "Project reveal content and case-study Reels build the trust needed for high-value bids."},
    {"id": "marketing_media", "label": "Marketing & media", "base": 58, "defaultOn": False,
     "why": "Already in the content game themselves \u2014 more likely a competitor or partner than a client."},
    {"id": "professional_services", "label": "Professional services", "base": 55, "defaultOn": True,
     "why": "LinkedIn content and personal-brand positioning helps these firms win higher-value clients."},
    {"id": "insurance_finance", "label": "Insurance & finance", "base": 48, "defaultOn": False,
     "why": "Trust-building content helps, but sales cycles are long and regulation limits creative freedom."},
    {"id": "it_tech_services", "label": "IT & telecom", "base": 46, "defaultOn": False,
     "why": "B2B and less visual \u2014 LinkedIn content can help, but it's a slower, harder social media sell."},
    {"id": "general_office", "label": "General offices", "base": 38, "defaultOn": False,
     "why": "Unclear business type and little visual content to build a social strategy around."},
    {"id": "logistics_transport", "label": "Logistics & transport", "base": 40, "defaultOn": False,
     "why": "Low visual appeal and mostly B2B \u2014 social media has less direct impact on their sales."},
    {"id": "banks_financial_institutions", "label": "Bank branches", "base": 35, "defaultOn": False,
     "why": "Heavily regulated and rarely the decision-maker for local marketing spend."},
]

# Each row: (osm_key, osm_value, sector_id, brand_required)
# brand_required=True filters out one-off independent shops for categories where
# they'd otherwise flood the results (e.g. every corner restaurant in a city).
TAGMAP = [
    # --- office ---
    ("office", "estate_agent", "real_estate", False),
    ("office", "insurance", "insurance_finance", False),
    ("office", "financial", "insurance_finance", False),
    ("office", "accountant", "professional_services", False),
    ("office", "tax_advisor", "professional_services", False),
    ("office", "advertising_agency", "marketing_media", False),
    ("office", "logistics", "logistics_transport", False),
    ("office", "moving_company", "logistics_transport", False),
    ("office", "courier", "logistics_transport", False),
    ("office", "company", "general_office", False),
    ("office", "coworking", "general_office", False),
    ("office", "lawyer", "professional_services", False),
    ("office", "notary", "professional_services", False),
    ("office", "consulting", "professional_services", False),
    ("office", "employment_agency", "professional_services", False),
    ("office", "recruitment", "professional_services", False),
    ("office", "architect", "professional_services", False),
    ("office", "engineer", "professional_services", False),
    ("office", "surveyor", "professional_services", False),
    ("office", "research", "professional_services", False),
    ("office", "it", "it_tech_services", False),
    ("office", "telecommunication", "it_tech_services", False),
    ("office", "newspaper", "marketing_media", False),
    ("office", "publisher", "marketing_media", False),
    # --- shop ---
    ("shop", "supermarket", "retail_chain", False),
    ("shop", "mall", "retail_chain", False),
    ("shop", "department_store", "retail_chain", False),
    ("shop", "variety_store", "retail_chain", False),
    ("shop", "doityourself", "retail_chain", False),
    ("shop", "convenience", "retail_general", False),
    ("shop", "car", "retail_big_ticket", False),
    ("shop", "motorcycle", "retail_big_ticket", False),
    ("shop", "appliance", "retail_big_ticket", False),
    ("shop", "electronics", "retail_big_ticket", False),
    ("shop", "furniture", "retail_big_ticket", False),
    ("shop", "jewelry", "retail_big_ticket", False),
    ("shop", "watches", "retail_big_ticket", False),
    ("shop", "tiles", "retail_big_ticket", False),
    ("shop", "carpet", "retail_big_ticket", False),
    ("shop", "bathroom_furnishing", "retail_big_ticket", False),
    ("shop", "kitchen", "retail_big_ticket", False),
    ("shop", "bed", "retail_big_ticket", False),
    ("shop", "car_parts", "retail_general", False),
    ("shop", "bicycle", "retail_general", False),
    ("shop", "hardware", "retail_general", False),
    ("shop", "clothes", "retail_general", False),
    ("shop", "shoes", "retail_general", False),
    ("shop", "fashion", "retail_general", False),
    ("shop", "bag", "retail_general", False),
    ("shop", "books", "retail_general", False),
    ("shop", "stationery", "retail_general", False),
    ("shop", "toys", "retail_general", False),
    ("shop", "games", "retail_general", False),
    ("shop", "video_games", "retail_general", False),
    ("shop", "sports", "retail_general", False),
    ("shop", "outdoor", "retail_general", False),
    ("shop", "pet", "retail_general", False),
    ("shop", "florist", "retail_general", False),
    ("shop", "garden_centre", "retail_general", False),
    ("shop", "houseware", "retail_general", False),
    ("shop", "lighting", "retail_general", False),
    ("shop", "curtain", "retail_general", False),
    ("shop", "gift", "retail_general", False),
    ("shop", "party", "retail_general", False),
    ("shop", "leather", "retail_general", False),
    ("shop", "fabric", "retail_general", False),
    ("shop", "sewing", "retail_general", False),
    ("shop", "e-cigarette", "retail_general", False),
    ("shop", "kiosk", "retail_general", False),
    ("shop", "newsagent", "retail_general", False),
    ("shop", "second_hand", "retail_general", False),
    ("shop", "charity", "retail_general", False),
    ("shop", "frame", "retail_general", False),
    ("shop", "trade", "retail_general", False),
    ("shop", "model", "retail_general", False),
    ("shop", "musical_instrument", "retail_general", False),
    ("shop", "music", "retail_general", False),
    ("shop", "art", "retail_general", False),
    ("shop", "video", "retail_general", False),
    ("shop", "computer", "retail_general", False),
    ("shop", "chemist", "retail_general", False),
    ("shop", "general", "retail_general", False),
    ("shop", "interior_decoration", "professional_services", False),
    ("shop", "travel_agency", "professional_services", False),
    ("shop", "copyshop", "professional_services", False),
    ("shop", "photo", "professional_services", False),
    ("shop", "storage_rental", "professional_services", False),
    ("shop", "funeral_directors", "professional_services", False),
    ("shop", "laundry", "trades_repair", False),
    ("shop", "dry_cleaning", "trades_repair", False),
    ("shop", "locksmith", "trades_repair", False),
    ("shop", "tyres", "trades_repair", False),
    ("shop", "mobile_phone", "retail_chain", True),
    ("shop", "hairdresser", "beauty_wellness", False),
    ("shop", "beauty", "beauty_wellness", False),
    ("shop", "cosmetics", "beauty_wellness", False),
    ("shop", "optician", "healthcare", False),
    ("shop", "bakery", "food_retail", False),
    ("shop", "butcher", "food_retail", False),
    ("shop", "greengrocer", "food_retail", False),
    ("shop", "deli", "food_retail", False),
    ("shop", "confectionery", "food_retail", False),
    ("shop", "seafood", "food_retail", False),
    ("shop", "alcohol", "food_retail", False),
    ("shop", "wine", "food_retail", False),
    ("shop", "coffee", "food_retail", False),
    ("shop", "tea", "food_retail", False),
    ("shop", "pastry", "food_retail", False),
    ("shop", "farm", "food_retail", False),
    ("shop", "pawnbroker", "banks_financial_institutions", False),
    ("shop", "money_lender", "banks_financial_institutions", False),
    ("shop", "bookmaker", "leisure_entertainment", False),
    # --- amenity ---
    ("amenity", "bank", "banks_financial_institutions", False),
    ("amenity", "bureau_de_change", "banks_financial_institutions", False),
    ("amenity", "hospital", "healthcare", False),
    ("amenity", "clinic", "healthcare", False),
    ("amenity", "dentist", "healthcare", False),
    ("amenity", "veterinary", "healthcare", False),
    ("amenity", "pharmacy", "healthcare", False),
    ("amenity", "doctors", "healthcare", False),
    ("amenity", "restaurant", "food_hospitality", True),
    ("amenity", "fast_food", "food_hospitality", True),
    ("amenity", "cafe", "food_hospitality", True),
    ("amenity", "bar", "food_hospitality", True),
    ("amenity", "pub", "food_hospitality", True),
    ("amenity", "ice_cream", "food_hospitality", True),
    ("amenity", "fuel", "retail_chain", True),
    ("amenity", "car_wash", "trades_repair", False),
    ("amenity", "car_rental", "logistics_transport", False),
    ("amenity", "cinema", "leisure_entertainment", False),
    ("amenity", "theatre", "leisure_entertainment", False),
    ("amenity", "nightclub", "leisure_entertainment", False),
    ("amenity", "casino", "leisure_entertainment", False),
    ("amenity", "gambling", "leisure_entertainment", False),
    ("amenity", "events_venue", "leisure_entertainment", False),
    ("amenity", "conference_centre", "professional_services", False),
    ("amenity", "university", "education_training", False),
    ("amenity", "college", "education_training", False),
    ("amenity", "driving_school", "education_training", False),
    ("amenity", "language_school", "education_training", False),
    ("amenity", "music_school", "education_training", False),
    ("amenity", "kindergarten", "childcare", False),
    ("amenity", "childcare", "childcare", False),
    ("amenity", "coworking_space", "general_office", False),
    ("amenity", "internet_cafe", "retail_general", False),
    ("amenity", "fitness_centre", "beauty_wellness", False),
    ("amenity", "gym", "beauty_wellness", False),
    ("amenity", "spa", "beauty_wellness", False),
    ("amenity", "marketplace", "retail_chain", False),
    ("amenity", "car_sharing", "logistics_transport", False),
    ("amenity", "taxi", "logistics_transport", False),
    # --- craft ---
    ("craft", "builder", "construction", False),
    ("craft", "electrician", "trades_repair", False),
    ("craft", "plumber", "trades_repair", False),
    ("craft", "carpenter", "trades_repair", False),
    ("craft", "hvac", "trades_repair", False),
    ("craft", "roofer", "trades_repair", False),
    ("craft", "painter", "trades_repair", False),
    ("craft", "tiler", "trades_repair", False),
    ("craft", "metal_construction", "trades_repair", False),
    ("craft", "locksmith", "trades_repair", False),
    ("craft", "photographer", "professional_services", False),
    ("craft", "tailor", "trades_repair", False),
    ("craft", "shoemaker", "trades_repair", False),
    ("craft", "upholsterer", "trades_repair", False),
    ("craft", "gardener", "trades_repair", False),
    ("craft", "brewery", "food_retail", False),
    ("craft", "winery", "food_retail", False),
    ("craft", "distillery", "food_retail", False),
    # --- healthcare ---
    ("healthcare", "hospital", "healthcare", False),
    ("healthcare", "clinic", "healthcare", False),
    ("healthcare", "dentist", "healthcare", False),
    ("healthcare", "physiotherapist", "healthcare", False),
    ("healthcare", "optometrist", "healthcare", False),
    ("healthcare", "alternative", "healthcare", False),
    ("healthcare", "laboratory", "healthcare", False),
    ("healthcare", "midwife", "healthcare", False),
    ("healthcare", "rehabilitation", "healthcare", False),
    ("healthcare", "psychotherapist", "healthcare", False),
    ("healthcare", "pharmacy", "healthcare", False),
    # --- tourism ---
    ("tourism", "hotel", "hospitality_lodging", False),
    ("tourism", "motel", "hospitality_lodging", False),
    ("tourism", "guest_house", "hospitality_lodging", False),
    ("tourism", "hostel", "hospitality_lodging", False),
    ("tourism", "apartment", "hospitality_lodging", False),
    ("tourism", "chalet", "hospitality_lodging", False),
    ("tourism", "zoo", "leisure_entertainment", False),
    ("tourism", "theme_park", "leisure_entertainment", False),
    ("tourism", "aquarium", "leisure_entertainment", False),
    ("tourism", "gallery", "professional_services", False),
    # --- leisure ---
    ("leisure", "fitness_centre", "beauty_wellness", False),
    ("leisure", "sports_centre", "leisure_entertainment", False),
    ("leisure", "golf_course", "leisure_entertainment", False),
    ("leisure", "water_park", "leisure_entertainment", False),
    ("leisure", "bowling_alley", "leisure_entertainment", False),
    ("leisure", "escape_game", "leisure_entertainment", False),
    ("leisure", "dance", "beauty_wellness", False),
]
